# coding=utf-8
from kivymd.app import MDApp
from kivy.uix.screenmanager import Screen, ScreenManager
from random import randint
from random import choice
from kivymd.uix.snackbar import Snackbar


class Gerenciador (ScreenManager):

    def change_screen(self, screen):
        self.current = screen


class Tela1 (Screen):
    pass

class Tela2 (Screen):

    def EuNuncaLeve(self):
        a =["Eu nunca fiquei bêbado","Eu nunca peidei em público","Eu nunca viajei de avião","Eu nunca matei aula",
            "Eu nunca menti para os meus pais","Eu nunca fiz uma aposta arriscada","Eu nunca dormi no cinema",
            "Eu nunca chorei ou flertei para me livrar de um problema","Eu nunca arruinei as férias de alguém",
            "Eu nunca peguei comida ou bebida em festa e levei para casa","Eu nunca caí porque estava olhando o celular",
            "Eu nunca caí porque estava olhando para um crush","Eu nunca tentei cortar meu cabelo e me arrependi",
            "Eu nunca me apaixonei à primeira vista","Eu nunca deletei comentários que eu não gostei nas minhas postagens",
            "Eu nunca disse que amo alguém sem querer ou sem sentir","Eu nunca peguei carona de estranhos",
            "Eu nunca gostei de uma música de Justin Bieber","Eu nunca estive acordado por dois dias seguidos",
            "Eu nunca fiz alguém ir para o hospital","Eu nunca segurei vela",
            "Eu nunca menti minha opinião para impressionar alguém","Eu nunca usei óculos sem lentes","Eu nunca fui pego colando",
            "Eu nunca tingi meu cabelo de uma cor bem forte","Eu nunca visitei um país em África","Eu nunca fiz bungee jumping",
            "Eu nunca fiquei mais de 2 dias sem tomar banho","Eu nunca apareci em vídeo no YouTube","Eu nunca desmaiei",
            "Eu nunca fiz piercing ou tatuagem","Eu nunca colei chiclete debaixo da mesa",
            "Eu nunca guardei chiclete para mascar depois","Eu nunca fui expulso de um bar","Eu nunca beijei um estranho",
            "Eu nunca comi algo escondido para não dividir","Eu nunca fingi que falava outro idioma","Eu nunca menti no currículo",
            "Eu nunca dei calote","Eu nunca levei calote","Eu nunca peguei emprestado e não devolvi","Eu nunca vi neve",
            "Eu nunca caí de moto e me ralei","Eu nunca me afoguei","Eu nunca me confessei na igreja","EU nunca ouvi música Gospel",
            "EU nunca fui em um rodeio","Eu nunca fiz perguntas para Siri","Eu nunca fiquei preso no elevador",
            "Eu nunca aprendi a andar de bicicleta","Eu nunca comecei a ver uma série só para ter assunto",
            "Eu nunca menti que uma comida estava boa","Eu nunca coloquei a culpa no cachorro","Eu nunca experimentei comida de cachorro",
            "Eu nunca dancei funk no meu quarto sem ninguém ver","Eu nunca treinei beijo de língua",
            "EU nunca cozinhei algo ruim e ofereci para me vingar de uma pessoa","Eu nunca subi em uma árvore",
            "Eu nunca mostrei a bunda em público","Eu nunca procurei perguntas para brincadeira eu nunca na internet",
            "Eu nunca dancei no palco de uma festa","Eu nunca invadi uma foto de alguém","Eu nunca tive medo de dormir sozinho",
            "Eu nunca passei mal de tanto comer","Eu nunca cantei em público","Eu nunca fui roubado","Eu nunca ganhei um sorteio",
            "Eu nunca brinquei de torta na cara","Eu nunca apareci na tv","Eu nunca espirrei catarro em público",
            "Eu nunca fui perseguido por animais","Eu nunca tive uma crise de riso em um momento sério",
            "Eu nunca misturei água na bebida para render mais","Eu nunca dei um soco em algo de vidro","Eu nunca recebi flores",
            "Eu nunca fui à Bahia","Eu nunca tive catapora","Eu nunca pensei que eu sou a pessoa mais linda dessa roda",
            "Eu nunca vi um animal selvagem","Eu nunca acampei","Eu nunca fiz uma fogueira","Eu nunca voei em um balão",
            "Eu nunca vomitei em um parque de diversões","Eu nunca cortei o meu próprio cabelo","Eu nunca invadi uma casa",
            "Eu nunca comi língua de boi","Eu nunca planejei um discurso no banho","Eu nunca fui a um baile funk",
            "Eu nunca fiquei com o irmão de um amigo","Eu nunca procurei o meu nome no Google","Eu nunca chorei no transporte público",
            "Eu nunca enviei uma carta de amor","Eu nunca fui o último a ser escolhido para alguma coisa","Eu nunca li a Bíblia","Eu nunca fui a um karaokê",
            "Eu nunca quebrei um osso","Eu nunca quebrei um dente","Eu nunca tive um cárie",
            "Eu nunca fui picado por uma abelha ou marimbondo","Eu nunca mastiguei gelo","Eu nunca comi jiló",
            "Eu nunca fiquei de recuperação","Eu nunca joguei jogos de guerra","Eu nunca chorei em um show","Eu nunca surfei",
            "Eu nunca mergulhei","Eu nunca vi o mar","Eu nunca vi o sol nascer","Eu nunca virei uma noite estudando",
            "Eu nunca tive um cachorro","Eu nunca tive um gato","Eu nunca tomei injeção no bumbum","Eu nunca encontrei alguém famoso",
            "Eu nunca fiz brincadeiras evangélicas","Eu nunca entendi uma piada e ri de mentira","Eu nunca fui queimado por uma água viva",
            "Eu nunca participei de um programa de auditório","Eu nunca caí na balada","Eu nunca cumprimentei alguém fingindo que sabia quem era",
            "EU nunca pratiquei esportes","EU nunca matei uma planta","Eu nunca levei uma ovada","Eu nunca joguei ovo em alguém",
            "Eu nunca tive piolho","Eu nunca tive pulga","Eu nunca matei uma barata","Eu nunca engoli algo que não era de comer",
            "Eu nunca pintei uma parede","Eu nunca apertei a campainha e saí correndo","Eu nunca perdi um voo",
            "Eu nunca entupi uma privada e não contei para ninguém","Eu nunca fingi que não vi alguém","Eu nunca caí em uma pegadinha","Eu nunca chorei em público",
            "Eu nunca tive infecção de urina","Eu nunca pulei a catraca para não pagar","Eu nunca menti no Eu Nunca","Eu nunca pulei Carnaval",
            "Eu nunca fiz uma viagem de carro de mais de 10 horas","Eu nunca perdi um brinquedo","Eu nunca ignorei um amigo no WhatsApp",
            "Eu nunca tirei foto com roupas emprestadas","Eu nunca comi até passar mal","Eu nunca tive medo de ser flagrado pela polícia",
            "Eu nunca rebolei até a boquinha da garrafa","Eu nunca caí em um golpe de internet","Eu nunca dancei axé",
            "Eu nunca joguei coisas pela sacada ou pela janela","Eu nunca caí da cama","Eu nuca tomei na mamadeira depois de adulto","Eu nunca quebrei uma promessa",
            "Eu nunca comi restos de comida da outra mesa","Eu nunca tive minhas redes sociais hackeadas","Eu nunca comi sorvete com batata frita",
            "Eu nunca menti que estava ocupado para não sair","Eu nunca fingi que estava falando no telefone","Eu nunca parei de comer carne","Eu nunca caí em um trote",
            "Eu nunca vi uma criatura extraterrestre","Eu nunca chamei alguém de brega","Eu nunca fiz brigadeiro","Eu nunca perdi um animal de estimação",
            "Eu nunca dancei agarradinho","Eu nunca naveguei em um barco","Eu nunca vi o mar","Eu nunca gostei de café","Eu nunca fui chamado de feio",
            "Eu nunca fiz uma pergunta anônima porque tinha vergonha","Eu nunca raspei o cabelo","Eu nunca plantei uma árvore","Eu nunca reciclei",
            "Eu nunca fiz perguntas constrangedoras","Eu nunca perdi um voo","Eu nunca tomei leite azedo","Eu nunca comi pizza no café da manhã",
            "Eu nunca tive uma câmera de fotos analógica","Eu nunca fui considerado o melhor em alguma coisa","Eu nunca fui considerado o pior em alguma coisa",
            "Eu nunca pintei uma parede","Eu nunca limpei um banheiro","Eu nunca costurei","Eu nunca fritei um ovo","Eu nunca misturei água no pote de shampoo",
            "Eu nunca usei perguntas para eu nunca de uma lista de perguntas,","Eu nunca acreditei no amor"]
        self.ids.txt.text=a[randint(0,184)]

    def EuNuncaPesado(self):
        a = ["Eu nunca enviei mensagens picantes para alguém",
            "Eu nunca aluguei filme para maiores de idade em uma locadora.",
            "Eu nunca beijei alguém do mesmo sexo",
            "Eu nunca beijei o(a) ex do meu melhor amigo(a)",
            "Eu nunca brochei",
            "Eu nunca Chamei o nome errado durante o sexo",
            "Eu nunca comprei um brinquedo de estimulação.",
            "Eu nunca corri da polícia.",
            "Eu nunca dancei no colo de ninguém.",
            "Eu nunca dirigi chapado.",
            "Eu nunca dirigi bêbado.",
            "Eu nunca enfiei o dedo em mim mesmo(a).",
            "Eu nunca engravidei",
            "Eu nunca entrei em coma alcoólico.",
            "Eu nunca enviei fotos nudes para a pessoa errada.",
            "Eu nunca enviei fotos sem roupas",
            "Eu nunca escondi uma marca no pescoço (feita por alguém com a boca) com uma blusa gola alta ou maquiagem.",
            "Eu nunca falsifiquei meus documentos.",
            "Eu nunca faltei ao trabalho porque estava morrendo de ressaca.",
            "Eu nunca fingi orgasmo.",
            "Eu nunca fiquei com alguém dessa roda",
            "Eu nunca fiquei com alguém dessa roda",
            "Eu nunca fiquei com alguém desta roda.",
            "Eu nunca fiquei com alguém na praia.",
            "Eu nunca fiquei com alguém na universidade.",
            "Eu nunca fiquei com alguém que eu nem sabia o nome.",
            "Eu nunca fiquei com gêmeos.",
            "Eu nunca fiquei com mais de uma pessoa ao mesmo tempo.",
            "Eu nunca fiquei com uma pessoa e depois nunca mais falei com ela.",
            "Eu nunca fiquei pelado em público.",
            "Eu nunca fiquei sem roupa na praia.",
            "Eu nunca fiquei tão bêbado que tiveram que me dar banho.",
            "Eu nunca fiquei tão louco que esqueci o próprio nome.",
            "Eu nunca fiz amor na piscina",
            "Eu nunca fiz sexo a 3",
            "Eu nunca fiz sexo na cama dos meus pais",
            "Eu nunca fiz teste de gravidez",
            "Eu nunca fiz um strip-tease para alguém",
            "Eu nunca flertei com um chefe na tentativa de obter uma promoção.",
            "Eu nunca flertei com uma pessoa casada",
            "Eu nunca fui carregado para casa depois de dar PT.",
            "Eu nunca fui infiel",
            "Eu nunca fui num clube para adultos.",
            "Eu nunca fui pego assistindo filmes para maiores de idade.",
            "Eu nunca fui pego fazendo sexo",
            "Eu nunca fui pego me brincando comigo mesmo.",
            "Eu nunca fui pego me masturbando",
            "Eu nunca fumei maconha",
            "Eu nunca fumei um cigarro de maconha.",
            "Eu nunca gravei vídeo enquanto estava transando com alguém.",
            "Eu nunca mandei a mesma fotografia para duas pessoas ao mesmo tempo.",
            "Eu nunca mandei fotos sem roupa para alguém.",
            "Eu nunca marquei de ficar com alguém do Tinder.",
            "Eu nunca matei algum animal com as próprias mãos.",
            "Eu nunca me excitei em lugar público",
            "Eu nunca me exibi na webcam",
            "Eu nunca passei coisas no cartão de crédito de alguém sem avisar",
            "Eu nunca precisei ir no médico devido a um objeto estranho preso dentro do meu corpo.",
            "Eu nunca quis ver meu parceiro ficando com outra pessoa.",
            "Eu nunca roubei em uma loja.",
            "Eu nunca sei drogas",
            "Eu nunca tirei a roupa em uma festa.",
            "Eu nunca tirei a roupa enquanto dançava para alguém.",
            "Eu nunca tive fantasias com os pés de alguém.",
            "Eu nunca tive medo de ter pego alguma DST.",
            "Eu nunca Tive orgasmos verdadeiros",
            "Eu nunca tive sexo com alguém muito mais velho",
            "Eu nunca tive sonhos eróticos",
            "Eu nunca tive um amigo colorido ou amigo com benefícios.",
            "Eu nunca tive um sonho intímo com algum professor.",
            "Eu nunca tive um sonho romântico com alguém que está aqui.",
            "Eu nunca tive uma fotografia imprópria vazada na internet.",
            "Eu nunca tomei a pílula do dia seguinte",
            "Eu nunca tomei banho com outra pessoa",
            "Eu nunca tomei banho com outra pessoa",
            "Eu nunca trai meu namorado(a)",
            "Eu nunca transei com alguém na cama dos meus pais.",
            "Eu nunca transei com alguém na rua.",
            "Eu nunca transei com alguém no banheiro de uma festa.",
            "Eu nunca transei menstruada",
            "Eu nunca transei na praia",
            "Eu nunca transei no cinema",
            "Eu nunca transei sem camisinha",
            "Eu nunca usei brinquedos sexuais",
            "Eu nunca usei drogas.",
            "Eu nunca usei o Tinder.",
            "Eu nunca vi algum vizinho pelado.",
            "Eu nunca vi duas pessoas transando.",
            "Eu nunca vi outro casal mantendo relações íntimas na minha frente.",
            "Eu nunca disse eu te amo apenas para ficar com alguém.",
            "Eu nunca dormi enquanto estava no meio de uma situação de intimidade com alguém.",
            "Eu nunca fiquei com alguém 20 anos mais velho que eu.",
            "Eu nunca fiquei com alguém do mesmo gênero que eu.",
            "Eu nunca flagrei meus vizinhos tendo relações íntimas.",
            "Eu nunca fui pego pela polícia fazendo algo ilícito.",
            "Eu nunca me senti atraído(a) pelo pai/mãe de algum amigo.",
            "Eu nunca ninguém dançou no meu colo.",
            "Eu nunca quis ficar com um casal de amigos.",
            "Eu nunca roubei alguma coisa e fui flagrado(a).",
            "Eu nunca usei alguma fruta ou legume para aliviar o stress do meu corpo.",
            "Eu nunca usei o Tinder enquanto namorava.",
            "Eu nunca usei uma fantasia ousada.",
            "Eu nunca vi meus pais em situações de intimidade extrema."]

        self.ids.txt.text=a[randint(0,102)]

class Tela3(Screen):
    global player
    player = []
    def cadastro (self,*args):
        if len(self.ids.user.text) != 0:
            player.append(self.ids.user.text)
            self.ids.user.text=""
        else:
            pass
    def Verdade (self):
        a =["Com quantas pessoas você já ficou na vida?",
            "O que você acha de 50 Tons de cinza?",
            "Já ficou com marca de chupão?",
            "Como foi a sua primeira vez?",
            "Já ficou com alguém da roda?",
            "Já nadou pelado?",
            "Já fez um strip-tease?",
            "Qual a diferença entre amor e sexo?",
            "Você tem alguma tatuagem escondida?",
            "Quem você beijaria dessa roda?",
            "Qual parte do corpo você beijaria da pessoa à sua esquerda?",
            "Se fosse para tirar uma peça de roupa da pessoa à sua direita, qual tiraria?",
            "Qual a sua cor de roupa íntima preferida?",
            "Qual sabor é gostoso de adicionar ao sexo oral?",
            "Quem é a pessoa mais sexy participando da brincadeira?",
            "Que tipo de pornografia te excita?",
            "Qual é a zona erógena do seu corpo que mais te excita?",
            "Cite uma pessoa do mesmo sexo que você, que você ficaria.",
            "Algemas ou vendas?",
            "Palavras te excitam? Quais?",
            "Você tem sonhos eróticos? Se lembra de algum recente?",
            "Que tipo de música é perfeito para transar?",
            "O que te faze gritar de tesão?",
            "Descreva o ambiente perfeito para uma noite de sexo.",
            "Luzes acesas, meia luz ou apagadas?",
            "O que você já fez no sexo que jamais faria de novo?",
            "O que te faz broxar?",
            "Qual o lugar mais inusitado que você já transou?",
            "Qual o lugar mais diferentão que você ainda quer transar nessa vida?",
            "Já fez sexo virtual?",
            "Já fez sexo por telefone?",
            "Você se lembra de quando começou a se tocar?",
            "Já fez sexo em um local público?",
            "Já transou com alguém do mesmo sexo?",
            "Amor ou sexo?",
            "Conte sobre a sua experiência sexual mais intensa.",
            "Qual o melhor tipo de lubrificante?",
            "Qual a pior experiência sexual que você já teve?",
            "Já transou em locais públicos?",
            "Já fez sexo na água?",
            "Em casa ou no motel?",
            "No carro ou no motel?",
            "Já foi a um sex-shop?",
            "O que você gosta ou gostaria de comprar um sex-shop?",
            "No sexo, é pior quando você fica sem gozar ou o quando o seu parceiro fica sem gozar?",
            "Mordida no pescoço ou lambida na orelha?",
            "Qual é a melhor coisa que alguém pode fazer na cama com você?",
            "Qual o maior período de tempo que você já ficou sem transar?",
            "Qual foi o máximo de vezes que você já transou em um dia?",
            "Já transou com mais de uma pessoa no mesmo dia?",
            "Já fez sexo causal?",
            "Já transou com alguém do Tinder ou app de paquera?",
            "Tem algum trauma sexual, qual?",
            "Já fez sexo no avião?",
            "Peito ou bunda?",
            "Já foi pego no flagra transando ou se masturbando?",
            "Você gosta de receber sexo oral?",
            "Já ficou com vontade de vomitar durante o sexo oral?",
            "Já fez sexo anal?",
            "Já teve orgasmos múltiplos?",
            "Já ficou com vontade de ir ao banheiro durante o sexo anal?",
            "Já ficou com alguém comprometido?",
            "Já fez sexo com mais de uma pessoa ao mesmo tempo?",
            "Já usou alguma coisa para lubrificar que não era lubrificante?",
            "Já deu ou recebeu um beijo grego? Tem vontade de experimentar?",
            "Qual brinquedinho erótico você gosta mais ou tem mais vontade de experimentar?",
            "Conte uma fantasia sexual sua.",
            "Dar ou receber sexo oral?",
            "Qual a sua posição sexual preferida?",
            "Qual a posiçao sexual que você menos gosta?",
            "Depilad@ ou com pelos?",
            "Qual a sua posição preferida para se masturbar?",
            "Já broxou?",
            "Já fingiu orgasmo?",
            "Qual a coisa mais estranha que já te pediram na hora H?",
            "Já participou de um trio ou sexo com mais pessoas?",
            "Trocaria parceiros?",
            "Se você pudesse repetir uma transa na sua vida, qual seria?",
            "O que é que você tem mais medo que te aconteça durante o sexo?",
            "Prefere sexo devagarzinho ou rápido?",
            "O que para você é proibido no sexo?",
            "Quanto tempo você costuma demorar para gozar?",
            "O que você gosta de escutar na hora do sexo?",
            "O que é sexo selvagem para você?",
            "Você toparia usar uma cueca comestível?",
            "O que é fundamental nas preliminares?",
            "Qual tipo de camisinha você gosta de usar?",
            "Prefere ficar por cima ou por baixo?",
            "Já transou na frente do espelho?",
            "O que você pensa sobre ser tocado na parte do trás?",
            "Já transou com alguém que acabou de conhecer?",
            "Qual o seu segredo para deixar alguém louco de tesão?",
            "Como foi a primeira vez que alguém te chupou?",
            "Qual o sexo mais louco que você já teve?",
            "Qual experiência sexual você prefere esquecer?",
            "No que você pensa quando está se masturbando?",
            "Você prefere dominar ou ser dominad@?",
            "Você já teve orgasmo enquanto dormia?",
            "Já usou Viagra?",
            "Você geme alto ou baixinho?"]
        self.ids.txt.text=a[randint(0,99)]
        if len(player) != 0:
            self.ids.Berlinda.text = "É a vez de ...."+(choice(player))
        else:
            pass

    def Desafio(self):
        a = ["Tomar um danoninho usando apenas a língua",
        "Fazer uma lap dance(dança no colo) para alguém da roda",
        "Dar uma aula de educação sexual de uma maneira muito sexy",
        "Colocar um preservativo em uma banana ou pepino",
        "Colocar um preservativo em uma fruta com a boca",
        "Massagear alguém da roda",
        "Faça uma massagem nas costas de alguém sem usar as mãos",
        "Tirar o sutiã sem tirar a camiseta",
        "Simule uma dança em pole dance",
        "Desabotoar o sutiã de alguém usando só uma mão",
        "Fingir um orgasmo",
        "Tirar a camiseta de alguém usando a boca",
        "Sussurrar uma frase sensual no ouvido de alguém",
        "Beijar a orelha de alguém da roda",
        "Fazer um discurso como se estivesse prestes à chegar a um orgasmo",
        "Poste uma foto fazendo cara de sensual no seu stories do Instagram",
        "Recitar um poema erótico",
        "Uma rodada fazendo cafuné em alguém da roda",
        "Explique onde está o clítoris",
        "Faça uma selfie sensual.",
        "Simule o seu olhar mais sexy para alguém da roda",
        "Tomar um shot no umbigo de alguém (body shot)",
        "Sussurre no ouvido de alguém as coisas que você costuma dizer na hora do sexo",
        "Morder (de leve) o pescoço de alguém da roda",
        "Com os olhos fechados, encoste a mão em alguém da roda e adivinhe qual é a parte do corpo",
        "Passar a próxima rodada no colo de alguém",
        "Chupar uma fruta como se fosse um órgão sexual",
        "Simule sexo oral com uma fruta",
        "Masturbar uma fruta com os dedos como se você estivesse falando com outra pessoa",
        "Com o consentimento, beije alguém da roda",
        "Simular um strip tease tirando uma peça de roupa",
        "Faça uma simulação no ar da sua posição sexual favorita",
        "Coloque um cubo de gelo na boca e dê um beijo no pescoço de alguém da roda",
        "Mande uma mensagem de voz sexy para seu crush",
        "Lamber alguma parte do corpo de outra pessoa",
        "Passe creme em alguém",
        "Feche os olhos, alguém da roda te dá um beijo, você precisa adivinhar quem é",
        "Mande uma mensagem para o crush perguntando se ele quer jogar verdade ou desafio virtual",
        "Envie um sticker sexy para seu crush",
        "Publique hoje eu tô soltinh@' no seu Facebook",
        "Receber cócegas de alguém por 1 minuto",
        "Envie para algum contatinho alguma das melhores cantadas do WhatsApp ",
        "Dançar na boquinha da garrafa (ou alguma dança do momento)",
        "Fingir que está na balada e mostrar como você faria para chegar em alguém ",
        "Mostrar as suas últimas mensagens do WhatsApp aqui na roda ",
        "Mostre a última foto que você tirou de você mesmo no celular ",
        "Fazer uma dança sensual usando só uma perna ",
        "Dançar em cima da mesa ",
        "Postar uma enquete no Stories do Instagram pedindo dicas de como parar uma diarreia ",
        "Faça um show de dança ao som do funk da moda ",
        "Mude o status de relacionamento no Facebook ",
        "Chegue para alguém desconhecido e comece a defender o político que você mais odeia."]
        self.ids.txt.text=a[randint(0,47)]
        if len(player) != 0:
            self.ids.Berlinda.text = "É a vez de ...."+(choice(player))
        else:
            pass
class Vaidarmerda(MDApp):
    def build(self):
        return Gerenciador()



Vaidarmerda().run()